bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: KBkoSiRQDIRHIUAK+Lg7NjciaKIKsV2/Rp7oHqtzuh55uuOlNH7qfnSBO+kwVe8zW2YdXurpRhNxXpPbwI0sbSRAXztOqgBBiExMeX6FTCVKV4Dj6MWP8pCMXlZChlUNRGB3wW7CVqYYbixKtSYziRmoQ5gIKNflz03Qvz2V2HJ+dP5D+H6XZtf/BjgNOc/qenRdbfOCdtdfrCDblZqJpXRX3bJNjqXbjfiHAGcK3trLkEjnWH1hZJJevPJqgZV/x2EW2wmFA4T8tOJk9KMJhIBWDM5DoUtR5+WYENSE9KiXSZAXl2rotiP/gwXwERQRKcLDw6RPnxg0bQaZ/K4ZDPk5fh8xttCsTKEI9wu+XHc5o1fuEHt1ZeprRMDtzDu9c4e38EsT30bu8VbzqxGJlWOQFF5bJe+jjvZlrmTlMTPcI8xsG3yj6bD+R+cy2z+PuuFW8y3WrC4+WBL++TCCTq7s2iKrx4KmnU5vmJ7SI1kMEIqudO0q1A5Wvl5BtpRs6j4SBvqcvhAEYIn+XzA8Nsj6voR2zKJpSew4MBpKoSAr+7qRI7u+sNbhaXz8xxxskHWUwPpg3MLIiB+6IPtRcgYT74vEul0PGG0ldx4uO+OXIDygWXKg1bdAw/wmZkCaag8jqqv6R6f5paHc7YBwpjETB4RLFaT9NUEwy4Aykw0=
conda_forge_output_validation: false
